name: ValheimRAFT Build

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2


      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - run: nuget restore ValheimMods.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Create Build Directory
        run: mkdir _build

      - name: Build Solution
        run: |
          msbuild.exe ValheimRAFT.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
